### ISSUE TITLE
composer failes during missing permissions

### ISSUE THREAD

**Issue by hanspagel** [servivum/vagrant-docker-box#1]
steps to reproduce:
1. vagrant up
2. vagrant ssh
3. docker ps
4. docker exec -ti {id of php container} bash
5. composer

root@c231bc1fa6cd:/var/www# composer
bash: /usr/local/bin/composer: Permission denied

actual permissions:
root@c231bc1fa6cd:/var/www# ls -alh /usr/local/bin/composer
-rw-r--r-- 1 root root 1.6M Apr 21 11:30 /usr/local/bin/composer

possible fix:
chmod +x /usr/local/bin/composer

**Comment by patrickbaber** [comment]
fixed with latest commit
